Update data_access_files.md
actigraph/CentrePoint3APIDocumentation pull request #38
Opened 2023-09-12 23:36 UTC by skyeli888

added ppg-green-100-hz

2023-09-13 12:56 UTC, RandyQuimby requested changes

2023-09-13 12:56 UTC, RandyQuimby commented on sections/data_access_files.md
> +|dataCategory|String|Values: raw-accelerometer, temperature, ppg-green, ppg-green-100-hz barometer, imu, ppg-red-ir-50-hz
missing a comma there after 100 hz

2023-09-14 13:12 UTC, RandyQuimby approved these changes

2023-09-14 13:14 UTC, hankdaniel approved these changes

2023-09-14 13:31 UTC, merged